# Generated by Django 4.2.7 on 2025-10-16 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Indian Rupees (₹)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
